version: '3.8'

services:
  # This is the name of our service (you can call it anything).
  web:
    # Tell Docker Compose to build the image from the Dockerfile in the current directory.
    build: .
    # Assign a name to the container for easy reference.
    container_name: paradise-grill-dev
    # Map port 5173 on your local machine to port 5173 inside the container.
    ports:
      - "5173:5173"
    # Set up volumes to sync your local code with the container's code.
    volumes:
      # This syncs your project folder to the /app directory in the container.
      - .:/app
      # This prevents the node_modules folder from your local machine (if it exists)
      # from overwriting the one installed inside the container.
      - /app/node_modules
